import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card.jsx'

export default function TeacherReportsPage() {
  return (
    <div className="acsis-view">
      <Card className="w-full border-border shadow-sm">
        <CardHeader>
          <CardTitle className="text-xl text-foreground">Reports</CardTitle>
          <CardDescription className="acsis-prose">
            Print student responses as PDF, add a generator line (e.g. &quot;Report generated by Prof. Jhun Alvarez as of
            March 12, 2026, at 11:00 AM&quot;), release scores after manual review, and email results with correct answers
            — wire this module to your backend when ready.
          </CardDescription>
        </CardHeader>
        <CardContent className="text-sm text-muted-foreground">Reporting tools will appear here once connected.</CardContent>
      </Card>
    </div>
  )
}
