import { useCallback, useEffect, useState } from 'react'
import { fetchAdminReports, reportTypeLabel } from '@/lib/adminReportsApi.js'
import { formatDateCreated } from '@/lib/adminUsersApi.js'
import { acsisToastError } from '@/lib/acsisToast.js'
import '../../pages/admin-ui/style.css'

export default function AdminReportsPage() {
  const [reports, setReports] = useState([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState(null)

  const load = useCallback(async () => {
    setLoading(true)
    setError(null)
    try {
      const data = await fetchAdminReports()
      setReports(data.reports || [])
    } catch (err) {
      setReports([])
      const msg = err instanceof Error ? err.message : 'Failed to load reports.'
      setError(msg)
      acsisToastError(msg)
    } finally {
      setLoading(false)
    }
  }, [])

  useEffect(() => {
    load()
  }, [load])

  return (
    <div className="acsis-stack">
      <div className="content-header">
        <div className="breadcrumb">
          <span className="brand-plp">PLP</span>
          <span className="brand-acsis"> ACSIS</span>
          <span className="sep">/</span>
          <span className="page-name">Reports</span>
        </div>
      </div>

      <div className="content-body">
        {error ? (
          <p className="um-banner-error" role="alert">
            {error}
          </p>
        ) : null}

        <div className="panel">
          <div className="panel-header">
            <span className="panel-title">Generated reports</span>
          </div>
          <p className="admin-settings-lead">
            Exam reports logged when faculty generate class results, individual, or item analysis exports.
          </p>
          <div className="um-table-wrapper">
            {loading ? (
              <p className="um-loading">Loading reports…</p>
            ) : reports.length === 0 ? (
              <p className="admin-placeholder-lead">No reports have been generated yet.</p>
            ) : (
              <table className="um-table">
                <thead>
                  <tr>
                    <th>Exam</th>
                    <th>Class</th>
                    <th>Type</th>
                    <th>Generated by</th>
                    <th>Date</th>
                  </tr>
                </thead>
                <tbody>
                  {reports.map((r) => (
                    <tr key={r.id}>
                      <td className="um-name">{r.examTitle}</td>
                      <td>{r.className}</td>
                      <td>{reportTypeLabel(r.reportType)}</td>
                      <td>{r.generatedByName}</td>
                      <td>{formatDateCreated(r.generatedAt)}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            )}
          </div>
        </div>
      </div>
    </div>
  )
}
