import PDFDocument from 'pdfkit'
import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'
import { listExamAuditLogsFilteredQuery } from '../repositories/teacherActivityRepository.js'
import { getMemberDisplayNameQuery } from '../repositories/examResultsRepository.js'
import {
  formatAuditDetails,
  formatAuditSectionLabel,
  labelForAuditEvent,
} from '../lib/examAuditEventLabels.js'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const googleSansRegularPath = path.join(__dirname, '../fonts/GoogleSans-Regular.ttf')
const googleSansBoldPath = path.join(__dirname, '../fonts/GoogleSans-Bold.ttf')

const PAGE_WIDTH = 595.28
const MARGIN = 48
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2
const ROW_PAD = 5

function setFont(doc, type = 'regular') {
  try {
    const fontPath = type === 'bold' ? googleSansBoldPath : googleSansRegularPath
    if (fs.existsSync(fontPath)) {
      doc.font(fontPath)
      return
    }
  } catch {
    /* fallback below */
  }
  doc.font(type === 'bold' ? 'Helvetica-Bold' : 'Helvetica')
}

function ensureSpace(doc, needed = 56) {
  if (doc.y > doc.page.height - MARGIN - needed) {
    doc.addPage()
  }
}

function formatPdfTime(iso) {
  if (!iso) return '—'
  try {
    return new Date(iso).toLocaleString('en-US', {
      month: 'short',
      day: 'numeric',
      year: 'numeric',
      hour: 'numeric',
      minute: '2-digit',
      hour12: true,
    })
  } catch {
    return '—'
  }
}

function formatGeneratedStatement(generatorName, date = new Date()) {
  const datePart = date.toLocaleDateString('en-US', {
    month: 'long',
    day: 'numeric',
    year: 'numeric',
  })
  const timePart = date.toLocaleTimeString('en-US', {
    hour: 'numeric',
    minute: '2-digit',
    hour12: true,
  })
  return `Report generated by ${generatorName} as of ${datePart}, at ${timePart}.`
}

function describeFilters(filters = {}) {
  const parts = []
  if (filters.eventType) parts.push(`Action: ${labelForAuditEvent(filters.eventType)}`)
  if (filters.examTitle) parts.push(`Quiz: ${filters.examTitle}`)
  if (filters.sectionLabel) parts.push(`Section: ${filters.sectionLabel}`)
  if (filters.dateFrom || filters.dateTo) {
    const from = filters.dateFrom || 'any'
    const to = filters.dateTo || 'any'
    parts.push(`Date: ${from} to ${to}`)
  }
  if (filters.search) parts.push(`Search: "${filters.search}"`)
  return parts.length ? parts.join(' · ') : 'All entries (no filters applied)'
}

function auditColWidths() {
  const fractions = [0.17, 0.16, 0.2, 0.14, 0.33]
  const widths = fractions.map((f) => Math.floor(CONTENT_WIDTH * f))
  const remainder = CONTENT_WIDTH - widths.reduce((sum, w) => sum + w, 0)
  widths[widths.length - 1] += remainder
  return widths
}

function drawTableHeader(doc, colWidths, labels) {
  const headerY = doc.y
  const headerHeight = 22
  doc.save()
  doc.rect(MARGIN, headerY, CONTENT_WIDTH, headerHeight).fill('#f3f4f6')
  doc.restore()

  setFont(doc, 'bold')
  doc.fontSize(8).fillColor('#374151')
  let x = MARGIN
  labels.forEach((label, index) => {
    doc.text(label, x + ROW_PAD, headerY + 7, {
      width: colWidths[index] - ROW_PAD * 2,
      lineBreak: false,
    })
    x += colWidths[index]
  })
  doc.y = headerY + headerHeight + 4
}

function drawTableRow(doc, colWidths, cells) {
  const rowY = doc.y
  const heights = cells.map((cell, index) =>
    doc.heightOfString(String(cell || '—'), {
      width: colWidths[index] - ROW_PAD * 2,
      align: 'left',
    }),
  )
  const rowHeight = Math.max(...heights, 12) + ROW_PAD * 2
  ensureSpace(doc, rowHeight + 8)

  let x = MARGIN
  setFont(doc, 'regular')
  doc.fontSize(8).fillColor('#111827')
  cells.forEach((cell, index) => {
    doc.text(String(cell || '—'), x + ROW_PAD, rowY + ROW_PAD, {
      width: colWidths[index] - ROW_PAD * 2,
      align: 'left',
    })
    x += colWidths[index]
  })

  doc
    .moveTo(MARGIN, rowY + rowHeight)
    .lineTo(MARGIN + CONTENT_WIDTH, rowY + rowHeight)
    .strokeColor('#e5e7eb')
    .lineWidth(0.5)
    .stroke()

  doc.y = rowY + rowHeight + 2
}

async function buildAuditLogsPdfBuffer({ logs, generatorName, filters, generatedAt = new Date() }) {
  const doc = new PDFDocument({ size: 'A4', margin: MARGIN })
  const chunks = []
  doc.on('data', (chunk) => chunks.push(chunk))

  const done = new Promise((resolve, reject) => {
    doc.on('end', () => resolve(Buffer.concat(chunks)))
    doc.on('error', reject)
  })

  setFont(doc, 'regular')
  doc.fontSize(8).fillColor('#6b7280')
  doc.text(formatGeneratedStatement(generatorName, generatedAt), MARGIN, MARGIN)
  doc.moveDown(1.2)

  setFont(doc, 'bold')
  doc.fontSize(16).fillColor('#111827')
  doc.text('Exam audit logs', MARGIN, doc.y)
  doc.moveDown(0.4)

  setFont(doc, 'regular')
  doc.fontSize(9).fillColor('#4b5563')
  doc.text(describeFilters(filters), MARGIN, doc.y, { width: CONTENT_WIDTH })
  doc.moveDown(0.3)
  doc.fontSize(9).fillColor('#6b7280')
  doc.text(`${logs.length} ${logs.length === 1 ? 'entry' : 'entries'}`, MARGIN, doc.y)
  doc.moveDown(0.8)

  const colWidths = auditColWidths()
  const headers = ['Time', 'Action', 'Quiz', 'Section', 'Details']
  drawTableHeader(doc, colWidths, headers)

  if (logs.length === 0) {
    setFont(doc, 'regular')
    doc.fontSize(9).fillColor('#6b7280')
    doc.text('No audit log entries match the current filters.', MARGIN, doc.y)
  } else {
    for (const log of logs) {
      drawTableRow(doc, colWidths, [
        formatPdfTime(log.occurredAt),
        labelForAuditEvent(log.eventType),
        log.examTitle || '—',
        formatAuditSectionLabel(log),
        formatAuditDetails(log),
      ])
    }
  }

  doc.end()
  return done
}

export async function exportTeacherActivityLogsService(teacherMemberId, filters = {}) {
  try {
    const logs = await listExamAuditLogsFilteredQuery(teacherMemberId, {
      limit: 500,
      eventType: filters.eventType || '',
      examId: filters.examId || '',
      sectionKey: filters.sectionKey || '',
      search: filters.search || '',
      dateFrom: filters.dateFrom || '',
      dateTo: filters.dateTo || '',
    })

    const generatorName = (await getMemberDisplayNameQuery(teacherMemberId)) || 'Teacher'
    const pdf = await buildAuditLogsPdfBuffer({
      logs,
      generatorName,
      filters,
      generatedAt: new Date(),
    })

    const stamp = new Date().toISOString().slice(0, 10)
    return {
      ok: true,
      contentType: 'application/pdf',
      filename: `acsis-audit-logs-${stamp}.pdf`,
      body: pdf,
      count: logs.length,
    }
  } catch (err) {
    console.error('[auditLogExportService.exportTeacherActivityLogs]', err)
    return { ok: false, status: 500, error: 'Failed to export audit logs.' }
  }
}
