import PDFDocument from 'pdfkit'
import { getExamWithQuestionsQuery } from '../repositories/examRepository.js'
import { getTeacherClassByIdQuery } from '../repositories/classRepository.js'
import {
  getExamSubmissionStatsQuery,
  getMemberDisplayNameQuery,
  getTopRankedSessionQuery,
  insertReportLogQuery,
  listExamSessionsForExamQuery,
  listCheatingLogsForExamQuery,
} from '../repositories/examResultsRepository.js'

const PAGE_WIDTH = 595.28
const MARGIN = 48
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2
const TABLE_CELL_PAD = 4

/** Column widths for student results — fills page width; Warnings gets extra space. */
function studentResultsColWidths() {
  const fractions = [0.055, 0.3, 0.135, 0.245, 0.085, 0.12]
  const widths = fractions.map((f) => Math.floor(CONTENT_WIDTH * f))
  const remainder = CONTENT_WIDTH - widths.reduce((sum, w) => sum + w, 0)
  widths[widths.length - 1] += remainder
  return widths
}

/** “Report generated by Prof. Jhun Alvarez as of March 12, 2026, at 11:00 AM.” */
function formatGeneratedStatement(generatorName, date = new Date()) {
  const datePart = date.toLocaleDateString('en-US', {
    month: 'long',
    day: 'numeric',
    year: 'numeric',
  })
  const timePart = date.toLocaleTimeString('en-US', {
    hour: 'numeric',
    minute: '2-digit',
    hour12: true,
  })
  return `Report generated by ${generatorName} as of ${datePart}, at ${timePart}.`
}

function sortSessionsForReport(sessions) {
  return [...sessions].sort((a, b) =>
    String(a.studentName || '').localeCompare(String(b.studentName || ''), undefined, {
      sensitivity: 'base',
    }),
  )
}

function ensureSpace(doc, needed = 48) {
  if (doc.y > doc.page.height - MARGIN - needed) {
    doc.addPage()
  }
}

function drawReportHeader(doc, { reportTitle, exam, className, generatorName, generatedAt }) {
  doc.font('Helvetica-Bold').fontSize(18).fillColor('#111827')
  doc.text(reportTitle, MARGIN, doc.y, { width: CONTENT_WIDTH, align: 'center' })
  doc.moveDown(0.6)

  doc.font('Helvetica').fontSize(10).fillColor('#374151')
  doc.text(formatGeneratedStatement(generatorName, generatedAt), MARGIN, doc.y, {
    width: CONTENT_WIDTH,
    align: 'center',
  })
  doc.moveDown(0.5)

  doc.fontSize(10).fillColor('#4b5563')
  doc.text(`Exam: ${exam.title || 'Untitled'}`, MARGIN, doc.y, { width: CONTENT_WIDTH, align: 'center' })
  doc.text(`Class: ${className || '—'}`, MARGIN, doc.y, { width: CONTENT_WIDTH, align: 'center' })
  doc.moveDown(1)

  doc.moveTo(MARGIN, doc.y).lineTo(MARGIN + CONTENT_WIDTH, doc.y).strokeColor('#d1d5db').stroke()
  doc.moveDown(0.75)
  doc.fillColor('#000')
}

function drawSectionTitle(doc, title) {
  ensureSpace(doc, 40)
  doc.font('Helvetica-Bold').fontSize(12).fillColor('#111827')
  doc.text(title, MARGIN, doc.y)
  doc.moveDown(0.4)
  doc.fillColor('#000')
}

function drawTable(doc, { headers, rows, colWidths }) {
  if (!rows.length) {
    doc.font('Helvetica').fontSize(9).fillColor('#6b7280').text('No records.', MARGIN, doc.y)
    doc.moveDown(0.5)
    return
  }

  const startX = MARGIN
  const headerH = 22
  const rowH = 20
  let y = doc.y

  const drawHeader = () => {
    doc.rect(startX, y, CONTENT_WIDTH, headerH).fill('#f3f4f6')
    doc.fillColor('#111827').font('Helvetica-Bold').fontSize(9)
    let x = startX + 6
    headers.forEach((label, i) => {
      doc.text(label, x, y + 7, { width: colWidths[i] - TABLE_CELL_PAD * 2, lineBreak: false })
      x += colWidths[i]
    })
    y += headerH
    doc.font('Helvetica').fontSize(8.5)
  }

  drawHeader()

  for (const row of rows) {
    if (y + rowH > doc.page.height - MARGIN - 20) {
      doc.addPage()
      y = MARGIN
      drawHeader()
    }
    let x = startX + 6
    row.forEach((cell, i) => {
      doc.fillColor('#1f2937').text(String(cell ?? '—'), x, y + 5, {
        width: colWidths[i] - TABLE_CELL_PAD * 2,
        lineBreak: false,
      })
      x += colWidths[i]
    })
    doc.strokeColor('#e5e7eb').lineWidth(0.5)
    doc.moveTo(startX, y + rowH).lineTo(startX + CONTENT_WIDTH, y + rowH).stroke()
    y += rowH
  }

  doc.y = y + 10
  doc.fillColor('#000')
}

function drawStatsBlock(doc, stats, top) {
  drawSectionTitle(doc, 'Summary')

  drawTable(doc, {
    headers: ['Metric', 'Count'],
    rows: [
      ['Enrolled', String(stats.enrolled ?? 0)],
      ['Joined', String(stats.joined ?? 0)],
      ['Submitted', String(stats.submitted ?? 0)],
    ],
    colWidths: [CONTENT_WIDTH * 0.55, CONTENT_WIDTH * 0.45],
  })

  if (top?.percentage != null) {
    doc.moveDown(0.25)
    doc.font('Helvetica').fontSize(10).fillColor('#15803d')
    doc.text(
      `Top 1: ${top.studentName} (${top.schoolId || '—'}) — ${top.percentage}% (${top.rawScore} pts)`,
      MARGIN,
      doc.y,
      { width: CONTENT_WIDTH, align: 'center' },
    )
    doc.fillColor('#000')
    doc.moveDown(0.5)
  }
}

function reviewStatusLabel(s) {
  if (s.status !== 'submitted') return '—'
  return s.reviewComplete ? 'Manually reviewed' : 'Auto-graded'
}

function scoreLabelForPdf(s) {
  if (s.status === 'submitted' && s.percentage != null) {
    return `${s.percentage}% (${s.rawScore}/${s.totalPoints})`
  }
  return '—'
}

function drawStudentResultsTable(doc, sessions) {
  drawSectionTitle(doc, 'Student results')

  const rows = sortSessionsForReport(sessions).map((s, index) => [
    String(index + 1),
    s.studentName || '—',
    s.schoolId || '—',
    scoreLabelForPdf(s),
    s.rank != null ? `#${s.rank}` : '—',
    String(s.warningCount ?? 0),
  ])

  drawTable(doc, {
    headers: ['No.', 'Student', 'School ID', 'Score', 'Rank', 'Warnings'],
    rows,
    colWidths: studentResultsColWidths(),
  })
}

function drawViolationsTable(doc, violations) {
  drawSectionTitle(doc, 'Integrity violations')

  const rows = violations.map((v) => [
    v.studentName || '—',
    v.eventType || '—',
    (v.details || '—').slice(0, 80),
    v.occurredAt ? new Date(v.occurredAt).toLocaleString('en-PH') : '—',
  ])

  drawTable(doc, {
    headers: ['Student', 'Event', 'Details', 'When'],
    rows,
    colWidths: [105, 70, 175, 95],
  })
}

function buildCsv(exam, sessions, violations, generatorName, generatedAt) {
  const lines = [
    formatGeneratedStatement(generatorName, generatedAt),
    `Exam,${JSON.stringify(exam.title || '')}`,
    '',
    'No.,Student,School ID,Status,Review,Score %,Raw,Total,Rank,Warnings',
  ]
  sortSessionsForReport(sessions).forEach((s, index) => {
    lines.push(
      [
        String(index + 1),
        JSON.stringify(s.studentName),
        JSON.stringify(s.schoolId || ''),
        s.status,
        reviewStatusLabel(s),
        s.percentage != null ? s.percentage : '',
        s.rawScore != null ? s.rawScore : '',
        s.totalPoints != null ? s.totalPoints : '',
        s.rank != null ? s.rank : '',
        s.warningCount,
      ].join(','),
    )
  })
  if (violations.length) {
    lines.push('', 'Violations', 'Student,Event,Details,When')
    for (const v of violations) {
      lines.push(
        [
          JSON.stringify(v.studentName),
          JSON.stringify(v.eventType),
          JSON.stringify(v.details || ''),
          JSON.stringify(v.occurredAt || ''),
        ].join(','),
      )
    }
  }
  return lines.join('\n')
}

function buildPdfBuffer({
  exam,
  className,
  sessions,
  stats,
  top,
  violations,
  generatorName,
  reportTitle,
  reportType,
  generatedAt,
}) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: MARGIN, size: 'A4' })
    const chunks = []
    doc.on('data', (c) => chunks.push(c))
    doc.on('end', () => resolve(Buffer.concat(chunks)))
    doc.on('error', reject)

    try {
      drawReportHeader(doc, { reportTitle, exam, className, generatorName, generatedAt })
      drawStatsBlock(doc, stats, top)

      if (reportType === 'violations') {
        drawViolationsTable(doc, violations)
      } else {
        drawStudentResultsTable(doc, sessions)
      }

      doc.end()
    } catch (err) {
      reject(err)
    }
  })
}

export async function exportExamReportService(
  classId,
  examId,
  teacherMemberId,
  { format = 'pdf', reportType = 'class_results' } = {},
) {
  try {
    const cls = await getTeacherClassByIdQuery(classId, teacherMemberId)
    if (!cls) {
      return { ok: false, status: 403, error: 'Access denied.' }
    }

    const exam = await getExamWithQuestionsQuery(classId, examId, false)
    if (!exam) {
      return { ok: false, status: 404, error: 'Exam not found.' }
    }

    const generatedAt = new Date()

    const [sessions, stats, violations, generatorName, top] = await Promise.all([
      listExamSessionsForExamQuery(classId, examId),
      getExamSubmissionStatsQuery(examId),
      listCheatingLogsForExamQuery(examId),
      getMemberDisplayNameQuery(teacherMemberId),
      getTopRankedSessionQuery(examId),
    ])

    const logType =
      reportType === 'violations'
        ? 'item_analysis'
        : reportType === 'detailed'
          ? 'individual'
          : 'class_results'

    await insertReportLogQuery(examId, teacherMemberId, logType)

    const className = cls.name || cls.courseCode || ''
    const reportTitle = 'Performance Report'

    const topForExport = top
      ? {
          studentName: top.studentName,
          schoolId: top.schoolId,
          percentage: top.percentage != null ? Number(top.percentage) : null,
          rawScore: top.rawScore != null ? Number(top.rawScore) : null,
        }
      : null

    if (format === 'csv') {
      const csv = buildCsv(exam, sessions, violations, generatorName, generatedAt)
      return {
        ok: true,
        contentType: 'text/csv; charset=utf-8',
        filename: `acsis-report-${examId}.csv`,
        body: Buffer.from(csv, 'utf8'),
      }
    }

    const pdf = await buildPdfBuffer({
      exam,
      className,
      sessions,
      stats,
      top: topForExport,
      violations,
      generatorName,
      reportTitle,
      reportType,
      generatedAt,
    })

    return {
      ok: true,
      contentType: 'application/pdf',
      filename: `acsis-report-${examId}-${reportType}.pdf`,
      body: pdf,
    }
  } catch (err) {
    console.error('[examReportService.exportExamReport]', err)
    return { ok: false, status: 500, error: 'Failed to export report.' }
  }
}
