import PDFDocument from 'pdfkit'
import ExcelJS from 'exceljs'
import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'
import SVGtoPDF from 'svg-to-pdfkit'
import { getExamWithQuestionsQuery } from '../repositories/examRepository.js'

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const acsisLogoPath = path.join(__dirname, '../../img/acsis-logo.svg');
const plpLogoPath = path.join(__dirname, '../../img/plpupdatedlogo 3.png');
const googleSansRegularPath = path.join(__dirname, '../fonts/GoogleSans-Regular.ttf');
const googleSansBoldPath = path.join(__dirname, '../fonts/GoogleSans-Bold.ttf');
import { getTeacherClassByIdQuery } from '../repositories/classRepository.js'
import {
  getExamSubmissionStatsQuery,
  getMemberDisplayNameQuery,
  getTopRankedSessionQuery,
  insertReportLogQuery,
  listExamSessionsForExamQuery,
  listCheatingLogsForExamQuery,
} from '../repositories/examResultsRepository.js'

const PAGE_WIDTH = 595.28
const MARGIN = 48
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2
const TABLE_CELL_PAD = 4

/** Column widths for student results — fills page width; Warnings gets extra space. */
function studentResultsColWidths() {
  const fractions = [0.055, 0.3, 0.135, 0.245, 0.085, 0.12]
  const widths = fractions.map((f) => Math.floor(CONTENT_WIDTH * f))
  const remainder = CONTENT_WIDTH - widths.reduce((sum, w) => sum + w, 0)
  widths[widths.length - 1] += remainder
  return widths
}

/** “Report generated by Prof. Jhun Alvarez as of March 12, 2026, at 11:00 AM.” */
function formatGeneratedStatement(generatorName, date = new Date()) {
  const datePart = date.toLocaleDateString('en-US', {
    month: 'long',
    day: 'numeric',
    year: 'numeric',
  })
  const timePart = date.toLocaleTimeString('en-US', {
    hour: 'numeric',
    minute: '2-digit',
    hour12: true,
  })
  return `Report generated by ${generatorName} as of ${datePart}, at ${timePart}.`
}

function sortSessionsForReport(sessions) {
  return [...sessions].sort((a, b) =>
    String(a.studentName || '').localeCompare(String(b.studentName || ''), undefined, {
      sensitivity: 'base',
    }),
  )
}

function ensureSpace(doc, needed = 48) {
  if (doc.y > doc.page.height - MARGIN - needed) {
    doc.addPage()
  }
}

function setFont(doc, type = 'regular') {
  try {
    const fontPath = type === 'bold' ? googleSansBoldPath : googleSansRegularPath;
    if (fs.existsSync(fontPath)) {
      doc.font(fontPath);
      return;
    }
  } catch (e) {}
  doc.font(type === 'bold' ? 'Helvetica-Bold' : 'Helvetica');
}

function drawReportHeader(doc, { exam, cls, generatorName, generatedAt, teacherLogoBase64, departmentName }) {
  // Tiny top header
  setFont(doc, 'regular');
  doc.fontSize(8).fillColor('#6b7280')
  doc.text(formatGeneratedStatement(generatorName, generatedAt), MARGIN, MARGIN, { align: 'left' })
  doc.moveDown(1.5)
  
  const currentY = doc.y;
  
  // Left aligned logos
  let nextLogoX = MARGIN;
  
  if (fs.existsSync(plpLogoPath)) {
    try {
      doc.image(plpLogoPath, nextLogoX, currentY, { fit: [60, 60] });
      nextLogoX += 75; // Increased spacing for larger logos
    } catch (e) {
      console.error('Failed to load PLP logo', e);
    }
  }
  
  if (teacherLogoBase64) {
    try {
      const buffer = Buffer.from(teacherLogoBase64.replace(/^data:image\/\w+;base64,/, ""), 'base64');
      doc.image(buffer, nextLogoX, currentY, { fit: [60, 60] });
    } catch (e) {
      console.error('Failed to load teacher logo', e);
    }
  }
  
  // Right aligned Institution name
  setFont(doc, 'bold');
  doc.fontSize(12).fillColor('#111827')
  doc.text('Pamantasan ng Lungsod ng Pasig', MARGIN, currentY + 8, { align: 'right', width: CONTENT_WIDTH })
  
  if (departmentName) {
    setFont(doc, 'regular');
    doc.fontSize(10).fillColor('#4b5563')
    doc.text(departmentName, MARGIN, doc.y, { align: 'right', width: CONTENT_WIDTH })
  }
  
  doc.y = Math.max(doc.y, currentY + 70);
  doc.moveTo(MARGIN, doc.y).lineTo(MARGIN + CONTENT_WIDTH, doc.y).strokeColor('#e5e7eb').stroke()
  doc.y += 15;
  
  // Title
  setFont(doc, 'bold');
  doc.fontSize(18).fillColor('#111827')
  doc.text(exam.title || 'Untitled Exam', { align: 'center', width: CONTENT_WIDTH })
  
  // Subtitle
  const className = cls.name || cls.courseCode || 'Class'
  const sectionLabel = cls.sectionCode ? ` — ${cls.sectionCode}` : '';
  const dateLabel = exam.scheduledStart ? new Date(exam.scheduledStart).toLocaleDateString('en-US') : (exam.createdAt ? new Date(exam.createdAt).toLocaleDateString('en-US') : '');
  const itemsCount = exam.questions ? exam.questions.length : 0;
  
  setFont(doc, 'regular');
  doc.fontSize(10).fillColor('#6b7280')
  doc.text(`${className}${sectionLabel} • AY ${cls.academicYear || ''}, Sem ${cls.semester || ''}`, { align: 'center', width: CONTENT_WIDTH })
  doc.text(`${dateLabel} • ${itemsCount} items`, { align: 'center', width: CONTENT_WIDTH })
  doc.moveDown(2);
}

function drawSectionTitle(doc, title) {
  ensureSpace(doc, 40)
  setFont(doc, 'bold');
  doc.fontSize(11).fillColor('#111827')
  doc.text(title, MARGIN, doc.y)
  doc.moveDown(0.5)
  doc.fillColor('#000')
}

function drawTable(doc, { headers, rows, colWidths }) {
  if (!rows.length) {
    doc.font('Helvetica').fontSize(9).fillColor('#6b7280').text('No records.', MARGIN, doc.y)
    doc.moveDown(0.5)
    return
  }

  const startX = MARGIN
  const headerH = 22
  const rowH = 20
  let y = doc.y

  const drawHeader = () => {
    doc.rect(startX, y, CONTENT_WIDTH, headerH).fill('#f3f4f6')
    doc.fillColor('#111827').font('Helvetica-Bold').fontSize(9)
    let x = startX + 6
    headers.forEach((label, i) => {
      doc.text(label, x, y + 7, { width: colWidths[i] - TABLE_CELL_PAD * 2, lineBreak: false })
      x += colWidths[i]
    })
    y += headerH
    doc.font('Helvetica').fontSize(8.5)
  }

  drawHeader()

  for (const row of rows) {
    if (y + rowH > doc.page.height - MARGIN - 20) {
      doc.addPage()
      y = MARGIN
      drawHeader()
    }
    let x = startX + 6
    row.forEach((cell, i) => {
      doc.fillColor('#1f2937').text(String(cell ?? '—'), x, y + 5, {
        width: colWidths[i] - TABLE_CELL_PAD * 2,
        lineBreak: false,
      })
      x += colWidths[i]
    })
    doc.strokeColor('#e5e7eb').lineWidth(0.5)
    doc.moveTo(startX, y + rowH).lineTo(startX + CONTENT_WIDTH, y + rowH).stroke()
    y += rowH
  }

  doc.y = y + 10
  doc.fillColor('#000')
}

function drawStatsBlock(doc, sessions) {
  const submittedSessions = sessions.filter(s => s.status === 'submitted' && s.percentage != null);
  let avgScore = '—', highest = '—', lowest = '—', passed = '—', failed = '—';
  if (submittedSessions.length > 0) {
    avgScore = Math.round(submittedSessions.reduce((acc, s) => acc + Number(s.percentage), 0) / submittedSessions.length) + '%';
    highest = Math.max(...submittedSessions.map(s => Number(s.percentage))) + '%';
    lowest = Math.min(...submittedSessions.map(s => Number(s.percentage))) + '%';
    passed = submittedSessions.filter(s => Number(s.percentage) >= 50).length;
    failed = submittedSessions.filter(s => Number(s.percentage) < 50).length;
  }
  
  const summaryLabels = ['Average', 'Highest', 'Lowest', 'Passed', 'Failed'];
  const summaryVals = [avgScore, highest, lowest, passed, failed];
  
  const colW = CONTENT_WIDTH / 5;
  const boxY = doc.y;
  doc.rect(MARGIN, boxY, CONTENT_WIDTH, 44).fillAndStroke('#f9fafb', '#e5e7eb');
  
  setFont(doc, 'bold');
  doc.fillColor('#111827').fontSize(14);
  for (let i = 0; i < 5; i++) {
    doc.text(String(summaryVals[i]), MARGIN + (i * colW), boxY + 10, { width: colW, align: 'center' });
  }
  setFont(doc, 'regular');
  doc.fillColor('#6b7280').fontSize(9);
  for (let i = 0; i < 5; i++) {
    doc.text(summaryLabels[i], MARGIN + (i * colW), boxY + 26, { width: colW, align: 'center' });
  }
  
  doc.y = boxY + 65;
  doc.fillColor('#000');
}

function reviewStatusLabel(s) {
  if (s.status !== 'submitted') return '—'
  return s.reviewComplete ? 'Manually reviewed' : 'Auto-graded'
}

function scoreLabelForPdf(s) {
  if (s.status === 'submitted' && s.percentage != null) {
    return `${s.percentage}% (${s.rawScore}/${s.totalPoints})`
  }
  return '—'
}

function drawStudentResultsTable(doc, sessions) {
  drawSectionTitle(doc, 'Student results')

  const rows = sortSessionsForReport(sessions).map((s, index) => [
    String(index + 1),
    s.studentName || '—',
    s.schoolId || '—',
    scoreLabelForPdf(s),
    s.rank != null ? `#${s.rank}` : '—',
    String(s.warningCount ?? 0),
  ])

  drawTable(doc, {
    headers: ['No.', 'Student', 'School ID', 'Score', 'Rank', 'Warnings'],
    rows,
    colWidths: studentResultsColWidths(),
  })
}

function drawViolationsTable(doc, violations) {
  drawSectionTitle(doc, 'Integrity violations')

  const rows = violations.map((v) => [
    v.studentName || '—',
    v.eventType || '—',
    (v.details || '—').slice(0, 80),
    v.occurredAt ? new Date(v.occurredAt).toLocaleString('en-PH') : '—',
  ])

  drawTable(doc, {
    headers: ['Student', 'Event', 'Details', 'When'],
    rows,
    colWidths: [105, 70, 175, 95],
  })
}

async function buildExcelBuffer({ exam, cls, sessions, violations, generatorName, generatedAt, reportType, teacherLogoBase64, departmentName }) {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = generatorName;
  workbook.created = generatedAt;
  
  const sheet = workbook.addWorksheet('Performance Report', { 
    views: [{ showGridLines: false }],
    pageSetup: { 
      paperSize: 9, // A4
      orientation: 'portrait',
      fitToPage: true,
      fitToWidth: 1,
      margins: { left: 0.7, right: 0.7, top: 0.75, bottom: 0.75, header: 0.3, footer: 0.3 }
    }
  });
  
  if (reportType === 'violations') {
    sheet.getColumn(1).width = 30; // Student
    sheet.getColumn(2).width = 20; // Event
    sheet.getColumn(3).width = 35; // Details
    sheet.getColumn(4).width = 18; // When
  } else {
    sheet.getColumn(1).width = 6;  // No.
    sheet.getColumn(2).width = 32; // Student
    sheet.getColumn(3).width = 15; // School ID
    sheet.getColumn(4).width = 18; // Score
    sheet.getColumn(5).width = 8;  // Rank
    sheet.getColumn(6).width = 10; // Warnings
  }

  // Row 1: generated at
  const genRow = sheet.addRow([formatGeneratedStatement(generatorName, generatedAt)]);
  genRow.font = { italic: true, size: 9, color: { argb: 'FF888888' } };
  sheet.mergeCells(`A1:F1`);
  genRow.height = 20;

  // Row 2: Institution
  const instRow = sheet.addRow(['', '', 'Institution: Pamantasan ng Lungsod ng Pasig']);
  instRow.font = { bold: true, size: 10, color: { argb: 'FF111827' } };
  sheet.mergeCells(`C2:F2`);
  instRow.getCell(3).alignment = { horizontal: 'right' };
  instRow.height = 25;

  // Row 3: Department
  const deptRow = sheet.addRow(['', '', departmentName ? `Department: ${departmentName}` : '']);
  if (departmentName) {
    deptRow.font = { size: 10, color: { argb: 'FF4B5563' } };
    sheet.mergeCells(`C3:F3`);
    deptRow.getCell(3).alignment = { horizontal: 'right' };
  }
  deptRow.height = 25;

  // Logos (placed at row 1 so they float over A2 and B2)
  let logoXOffset = 0;
  if (fs.existsSync(plpLogoPath)) {
    try {
      const plpLogoId = workbook.addImage({ filename: plpLogoPath, extension: 'png' });
      sheet.addImage(plpLogoId, { tl: { col: 0, row: 1 }, ext: { width: 60, height: 60 } });
      logoXOffset += 1.2; // Use fractional offset to add a nice gap
    } catch(e) {}
  }
  
  if (teacherLogoBase64) {
    try {
      const b64Data = teacherLogoBase64.replace(/^data:image\/\w+;base64,/, "");
      const extMatch = teacherLogoBase64.match(/^data:image\/(\w+);base64,/);
      const ext = extMatch ? extMatch[1] : 'png';
      const teacherLogoId = workbook.addImage({ base64: b64Data, extension: ext });
      sheet.addImage(teacherLogoId, { tl: { col: logoXOffset, row: 1 }, ext: { width: 60, height: 60 } });
    } catch(e) {}
  }

  sheet.addRow([]);

  const titleRow = sheet.addRow([exam.title || 'Untitled Exam']);
  titleRow.font = { bold: true, size: 16, color: { argb: 'FF111827' } };
  sheet.mergeCells(`A5:F5`);
  titleRow.alignment = { horizontal: 'center' };
  
  const className = cls.name || cls.courseCode || 'Class'
  const sectionLabel = cls.sectionCode ? ` — ${cls.sectionCode}` : '';
  const dateLabel = exam.scheduledStart ? new Date(exam.scheduledStart).toLocaleDateString('en-US') : (exam.createdAt ? new Date(exam.createdAt).toLocaleDateString('en-US') : '');
  const itemsCount = exam.questions ? exam.questions.length : 0;
  
  const sub1 = sheet.addRow([`${className}${sectionLabel} • AY ${cls.academicYear || ''}, Sem ${cls.semester || ''}`]);
  const sub2 = sheet.addRow([`${dateLabel} • ${itemsCount} items`]);
  sub1.font = { size: 10, color: { argb: 'FF6B7280' } };
  sub1.alignment = { horizontal: 'center' };
  sheet.mergeCells(`A${sub1.number}:F${sub1.number}`);
  
  sub2.font = { size: 10, color: { argb: 'FF6B7280' } };
  sub2.alignment = { horizontal: 'center' };
  sheet.mergeCells(`A${sub2.number}:F${sub2.number}`);

  sheet.addRow([]);
  
  const submittedSessions = sessions.filter(s => s.status === 'submitted' && s.percentage != null);
  let avgScore = '—', highest = '—', lowest = '—', passed = '—', failed = '—';
  if (submittedSessions.length > 0) {
    avgScore = Math.round(submittedSessions.reduce((acc, s) => acc + Number(s.percentage), 0) / submittedSessions.length) + '%';
    highest = Math.max(...submittedSessions.map(s => Number(s.percentage))) + '%';
    lowest = Math.min(...submittedSessions.map(s => Number(s.percentage))) + '%';
    passed = submittedSessions.filter(s => Number(s.percentage) >= 50).length;
    failed = submittedSessions.filter(s => Number(s.percentage) < 50).length;
  }
  
  // Summary Block
  const statLabelRow = sheet.addRow(['Average', 'Highest', 'Lowest', 'Passed', 'Failed', '']);
  const statValRow = sheet.addRow([avgScore, highest, lowest, passed, failed, '']);
  
  statLabelRow.font = { size: 10, color: { argb: 'FF6B7280' } };
  statLabelRow.alignment = { horizontal: 'center' };
  
  statValRow.font = { bold: true, size: 14, color: { argb: 'FF111827' } };
  statValRow.alignment = { horizontal: 'center' };
  
  // apply light background to stats block
  for (let col = 1; col <= 5; col++) {
    const cellL = statLabelRow.getCell(col);
    const cellV = statValRow.getCell(col);
    cellL.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF9FAFB' } };
    cellV.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF9FAFB' } };
    
    // Add thin border around the stats block
    const border = {
      top: { style: 'thin', color: { argb: 'FFE5E7EB' } },
      bottom: { style: 'thin', color: { argb: 'FFE5E7EB' } },
      left: { style: 'thin', color: { argb: 'FFE5E7EB' } },
      right: { style: 'thin', color: { argb: 'FFE5E7EB' } }
    };
    cellL.border = border;
    cellV.border = border;
  }

  sheet.addRow([]);
  sheet.addRow([]);

  // Function to style headers
  const styleTableHeader = (row) => {
    row.font = { bold: true, size: 10, color: { argb: 'FF111827' } };
    row.eachCell((cell) => {
      cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF3F4F6' } };
      cell.border = {
        top: { style: 'thin', color: { argb: 'FFD1D5DB' } },
        bottom: { style: 'thin', color: { argb: 'FFD1D5DB' } },
      };
      cell.alignment = { vertical: 'middle', horizontal: 'left' };
    });
  };

  const styleTableRow = (row) => {
    row.font = { size: 10, color: { argb: 'FF1F2937' } };
    row.eachCell((cell) => {
      cell.border = {
        bottom: { style: 'thin', color: { argb: 'FFE5E7EB' } }
      };
      cell.alignment = { vertical: 'middle', horizontal: 'left' };
    });
  };
  
  // Data
  if (reportType === 'violations') {
    const headerTitleRow = sheet.addRow(['Integrity Violations']);
    headerTitleRow.font = { bold: true, size: 12, color: { argb: 'FF111827' } };
    sheet.addRow([]);

    const headerRow = sheet.addRow(['Student', 'Event', 'Details', 'When', '', '']);
    styleTableHeader(headerRow);
    
    for (const v of violations) {
      const dataRow = sheet.addRow([
        v.studentName || '—',
        v.eventType || '—',
        v.details || '—',
        v.occurredAt ? new Date(v.occurredAt).toLocaleString('en-PH') : '—',
        '',
        ''
      ]);
      styleTableRow(dataRow);
    }
  } else {
    const headerTitleRow = sheet.addRow(['Student Results']);
    headerTitleRow.font = { bold: true, size: 12, color: { argb: 'FF111827' } };
    sheet.addRow([]);

    const headerRow = sheet.addRow(['No.', 'Student', 'School ID', 'Score', 'Rank', 'Warnings']);
    styleTableHeader(headerRow);

    sortSessionsForReport(sessions).forEach((s, index) => {
      const scoreLabel = s.status === 'submitted' && s.percentage != null 
        ? `${s.percentage}% (${s.rawScore}/${s.totalPoints})`
        : '—';
      const rankLabel = s.rank != null ? `#${s.rank}` : '—';
      const dataRow = sheet.addRow([
        index + 1,
        s.studentName || '—',
        s.schoolId || '—',
        scoreLabel,
        rankLabel,
        s.warningCount || 0
      ]);
      styleTableRow(dataRow);
    });
  }

  return await workbook.xlsx.writeBuffer();
}

function buildPdfBuffer({
  exam,
  cls,
  sessions,
  stats,
  top,
  violations,
  generatorName,
  reportTitle,
  reportType,
  generatedAt,
  teacherLogoBase64,
  departmentName
}) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: MARGIN, size: 'A4', bufferPages: true })
    const chunks = []
    doc.on('data', (c) => chunks.push(c))
    doc.on('end', () => resolve(Buffer.concat(chunks)))
    doc.on('error', reject)

    try {
      drawReportHeader(doc, { exam, cls, generatorName, generatedAt, teacherLogoBase64, departmentName })
      drawStatsBlock(doc, sessions)

      if (reportType === 'violations') {
        drawViolationsTable(doc, violations)
      } else {
        drawStudentResultsTable(doc, sessions)
      }
      
      const pages = doc.bufferedPageRange();
      for (let i = 0; i < pages.count; i++) {
        doc.switchToPage(i);
        
        const oldBottomMargin = doc.page.margins.bottom;
        doc.page.margins.bottom = 0;
        
        const footerY = doc.page.height - 30;
        
        try {
          if (fs.existsSync(acsisLogoPath)) {
            const svgContent = fs.readFileSync(acsisLogoPath, 'utf8');
            SVGtoPDF(doc, svgContent, MARGIN, footerY - 5, { width: 14, height: 14 });
          }
        } catch (err) {
          // ignore
        }
        
        setFont(doc, 'bold');
        doc.fontSize(9).fillColor('#9ca3af');
        doc.text('via ACSIS', MARGIN + 20, footerY, { align: 'left', lineBreak: false });
        
        doc.page.margins.bottom = oldBottomMargin;
      }

      doc.end()
    } catch (err) {
      reject(err)
    }
  })
}

export async function exportExamReportService(
  classId,
  examId,
  teacherMemberId,
  { format = 'pdf', reportType = 'class_results', teacherLogoBase64, departmentName } = {},
) {
  try {
    const cls = await getTeacherClassByIdQuery(classId, teacherMemberId)
    if (!cls) {
      return { ok: false, status: 403, error: 'Access denied.' }
    }

    const exam = await getExamWithQuestionsQuery(classId, examId, false)
    if (!exam) {
      return { ok: false, status: 404, error: 'Exam not found.' }
    }

    const generatedAt = new Date()

    const [sessions, stats, violations, teacherInfo, top] = await Promise.all([
      listExamSessionsForExamQuery(classId, examId),
      getExamSubmissionStatsQuery(examId),
      listCheatingLogsForExamQuery(examId),
      getMemberDisplayNameQuery(teacherMemberId),
      getTopRankedSessionQuery(examId),
    ])
    const generatorName = teacherInfo.name

    const logType =
      reportType === 'violations'
        ? 'item_analysis'
        : reportType === 'detailed'
          ? 'individual'
          : 'class_results'

    await insertReportLogQuery(examId, teacherMemberId, logType)

    const className = cls.name || cls.courseCode || ''
    const reportTitle = 'Performance Report'

    const topForExport = top
      ? {
          studentName: top.studentName,
          schoolId: top.schoolId,
          percentage: top.percentage != null ? Number(top.percentage) : null,
          rawScore: top.rawScore != null ? Number(top.rawScore) : null,
        }
      : null

    if (format === 'excel') {
      const excelBuffer = await buildExcelBuffer({
        exam,
        cls,
        sessions,
        violations,
        generatorName,
        generatedAt,
        reportType,
        teacherLogoBase64,
        departmentName,
      })

      return {
        ok: true,
        contentType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        filename: `acsis-report-${examId}.xlsx`,
        body: excelBuffer,
      }
    }

    const pdf = await buildPdfBuffer({
      exam,
      cls,
      sessions,
      stats,
      top: topForExport,
      violations,
      generatorName,
      reportTitle,
      reportType,
      generatedAt,
      teacherLogoBase64,
      departmentName,
    })

    return {
      ok: true,
      contentType: 'application/pdf',
      filename: `acsis-report-${examId}-${reportType}.pdf`,
      body: pdf,
    }
  } catch (err) {
    console.error('[examReportService.exportExamReport]', err)
    return { ok: false, status: 500, error: 'Failed to export report.' }
  }
}
