import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card.jsx'

export default function StudentReportsPage() {
  return (
    <div className="acsis-view">
      <Card className="w-full border-border shadow-sm">
        <CardHeader>
          <CardTitle className="text-xl text-foreground">Reports</CardTitle>
          <CardDescription>
            Instructors will be able to print PDF responses, add a header such as &quot;Report generated by Prof. Jhun
            Alvarez as of March 12, 2026, at 11:00 AM&quot;, release scores manually, and send results with correct answers
            to the student&apos;s registered email. This module will connect to your backend when implemented.
          </CardDescription>
        </CardHeader>
        <CardContent className="text-sm text-muted-foreground">No reports to show yet.</CardContent>
      </Card>
    </div>
  )
}
