import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'
import SVGtoPDF from 'svg-to-pdfkit'
import { formatSemesterLabel } from './termLabel.js'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

export const PAGE_WIDTH = 595.28
export const MARGIN = 48
export const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2

const acsisLogoPath = path.join(__dirname, '../../img/acsis-logo.svg')
const plpLogoPath = path.join(__dirname, '../../img/plpupdatedlogo 3.png')
const googleSansRegularPath = path.join(__dirname, '../fonts/GoogleSans-Regular.ttf')
const googleSansBoldPath = path.join(__dirname, '../fonts/GoogleSans-Bold.ttf')

/** “Report generated by Prof. Jhun Alvarez as of March 12, 2026, at 11:00 AM.” */
export function formatGeneratedStatement(generatorName, date = new Date()) {
  const datePart = date.toLocaleDateString('en-US', {
    month: 'long',
    day: 'numeric',
    year: 'numeric',
  })
  const timePart = date.toLocaleTimeString('en-US', {
    hour: 'numeric',
    minute: '2-digit',
    hour12: true,
  })
  return `Report generated by ${generatorName} as of ${datePart}, at ${timePart}.`
}

export function ensureSpace(doc, needed = 48) {
  if (doc.y > doc.page.height - MARGIN - needed) {
    doc.addPage()
  }
}

export function setFont(doc, type = 'regular') {
  try {
    const fontPath = type === 'bold' ? googleSansBoldPath : googleSansRegularPath
    if (fs.existsSync(fontPath)) {
      doc.font(fontPath)
      return
    }
  } catch {
    /* fall through */
  }
  doc.font(type === 'bold' ? 'Helvetica-Bold' : 'Helvetica')
}

export function drawReportHeader(
  doc,
  {
    exam,
    cls,
    generatorName,
    generatedAt,
    teacherLogoBase64,
    departmentName,
    subtitleLines,
    compact = false,
    pageMargin = MARGIN,
    pageWidth = PAGE_WIDTH,
  },
) {
  const contentWidth = pageWidth - pageMargin * 2
  const logoSize = compact ? 42 : 60
  const logoRowHeight = compact ? 48 : 70
  const dividerPad = compact ? 8 : 15
  const titleSize = compact ? 15 : 18
  const afterTitleGap = compact ? 0.65 : 2

  setFont(doc, 'regular')
  doc.fontSize(compact ? 7 : 8).fillColor('#6b7280')
  doc.text(formatGeneratedStatement(generatorName, generatedAt), pageMargin, pageMargin, { align: 'left' })
  doc.moveDown(compact ? 0.55 : 1.5)

  const currentY = doc.y
  let nextLogoX = pageMargin

  if (fs.existsSync(plpLogoPath)) {
    try {
      doc.image(plpLogoPath, nextLogoX, currentY, { fit: [logoSize, logoSize] })
      nextLogoX += logoSize + (compact ? 10 : 15)
    } catch (e) {
      console.error('Failed to load PLP logo', e)
    }
  }

  if (teacherLogoBase64) {
    try {
      const buffer = Buffer.from(teacherLogoBase64.replace(/^data:image\/\w+;base64,/, ''), 'base64')
      doc.image(buffer, nextLogoX, currentY, { fit: [logoSize, logoSize] })
    } catch (e) {
      console.error('Failed to load teacher logo', e)
    }
  }

  setFont(doc, 'bold')
  doc.fontSize(compact ? 10 : 12).fillColor('#111827')
  doc.text('Pamantasan ng Lungsod ng Pasig', pageMargin, currentY + (compact ? 4 : 8), {
    align: 'right',
    width: contentWidth,
  })

  if (departmentName) {
    setFont(doc, 'regular')
    doc.fontSize(compact ? 9 : 10).fillColor('#4b5563')
    doc.text(departmentName, pageMargin, doc.y, { align: 'right', width: contentWidth })
  }

  doc.y = Math.max(doc.y, currentY + logoRowHeight)
  doc.moveTo(pageMargin, doc.y).lineTo(pageMargin + contentWidth, doc.y).strokeColor('#e5e7eb').stroke()
  doc.y += dividerPad

  setFont(doc, 'bold')
  doc.fontSize(titleSize).fillColor('#111827')
  doc.text(exam.title || 'Untitled Exam', { align: 'center', width: contentWidth })

  const className = cls.name || cls.courseCode || 'Class'
  const sectionLabel = cls.sectionCode ? ` — ${cls.sectionCode}` : ''
  const dateLabel = exam.scheduledStart
    ? new Date(exam.scheduledStart).toLocaleDateString('en-US')
    : (exam.createdAt ? new Date(exam.createdAt).toLocaleDateString('en-US') : '')
  const itemsCount = exam.questions ? exam.questions.length : 0

  if (subtitleLines !== undefined) {
    if (subtitleLines.length > 0) {
      setFont(doc, 'regular')
      doc.fontSize(compact ? 9 : 10).fillColor('#6b7280')
      for (const line of subtitleLines) {
        if (line) doc.text(line, { align: 'center', width: contentWidth })
      }
    }
  } else {
    setFont(doc, 'regular')
    doc.fontSize(compact ? 9 : 10).fillColor('#6b7280')
    doc.text(`${className}${sectionLabel} • AY ${cls.academicYear || ''}, ${formatSemesterLabel(cls.semester)}`, {
      align: 'center',
      width: contentWidth,
    })
    doc.text(`${dateLabel} • ${itemsCount} items`, { align: 'center', width: contentWidth })
  }

  doc.moveDown(afterTitleGap)
}

export function stampReportFooters(doc) {
  const pages = doc.bufferedPageRange()
  for (let i = 0; i < pages.count; i++) {
    doc.switchToPage(i)

    const oldBottomMargin = doc.page.margins.bottom
    doc.page.margins.bottom = 0

    const footerY = doc.page.height - 30

    try {
      if (fs.existsSync(acsisLogoPath)) {
        const svgContent = fs.readFileSync(acsisLogoPath, 'utf8')
        SVGtoPDF(doc, svgContent, MARGIN, footerY - 5, { width: 14, height: 14 })
      }
    } catch {
      /* ignore */
    }

    setFont(doc, 'bold')
    doc.fontSize(9).fillColor('#9ca3af')
    doc.text('via ACSIS', MARGIN + 20, footerY, { align: 'left', lineBreak: false })

    doc.page.margins.bottom = oldBottomMargin
  }
}
